Fixing windows build break issue
Summary:
Meta internal llvm change cause windows build break. In this diff, I am fixing the windows build.

https://www.internalfb.com/sandcastle/workflow/1193453901260434331/artifact/actionlog.1193453901388558993.stdout.1?selectedLines=5810-5822-1-94

```
FAILED: tools/lldb/tools/lldb-dap/CMakeFiles/lldb-dap.dir/Transport.cpp.obj
C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_STATIC -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ID:\full-fbsource\temp_dir\llvm-project\build\tools\lldb\tools\lldb-dap -ID:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap -ID:\full-fbsource\temp_dir\llvm-project\lldb\include -ID:\full-fbsource\temp_dir\llvm-project\build\tools\lldb\include -ID:\full-fbsource\temp_dir\llvm-project\build\include -ID:\full-fbsource\temp_dir\llvm-project\llvm\include -IC:\tools\fb-python\fb-python312\include -ID:\full-fbsource\temp_dir\llvm-project\llvm\..\clang\include -ID:\full-fbsource\temp_dir\llvm-project\build\tools\lldb\..\clang\include -ID:\full-fbsource\xplat\third-party\xz\src\liblzma\api -DLZMA_API_STATIC /Zc:inline /Zc:preprocessor /Zc:__cplusplus /Oi /bigobj /permissive- /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd5105 -wd4324 -wd4251 -wd4275 -w14062 -we4238 /Gw /O2 /Ob2 /DNDEBUG -MD   -wd4018 -wd4068 -wd4150 -wd4201 -wd4251 -wd4521 -wd4530 -wd4589  /EHs-c- /GR- -std:c++17 /showIncludes /Fotools\lldb\tools\lldb-dap\CMakeFiles\lldb-dap.dir\Transport.cpp.obj /Fdtools\lldb\tools\lldb-dap\CMakeFiles\lldb-dap.dir\ /FS -c D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(41): error C2065: 'fd_set': undeclared identifier
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(41): error C2146: syntax error: missing ';' before identifier 'read_fds'
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(41): error C2065: 'read_fds': undeclared identifier
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(44): error C2079: 'tv' uses undefined struct 'waitDataAvailableOrTimeout::timeval'
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(50): error C2065: 'read_fds': undeclared identifier
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(50): error C3861: 'FD_ZERO': identifier not found
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(51): error C2065: 'read_fds': undeclared identifier
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(51): error C3861: 'FD_SET': identifier not found
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(54): error C2065: 'read_fds': undeclared identifier
D:\full-fbsource\temp_dir\llvm-project\lldb\tools\lldb-dap\Transport.cpp(54): error C3861: 'select': identifier not found
[5164/5223] Building CXX object tools\lldb\tools\lldb-dap\CMakeFiles\lldb-dap.dir\DAP.cpp.obj
```

Test Plan: https://www.internalfb.com/sandcastle/workflow/3152519739166693775

Reviewers: davidayoung, cssmith, #lldb_team, isushi, #rl_devinfra_dde

Reviewed By: davidayoung

Subscribers: satyajanga, hyubo

Differential Revision: https://phabricator.intern.facebook.com/D74296533

Tasks: T223535126