[REVERT WHEN 137041 LANDS][GDBServer/PTRACE SEIZE] Implement internal prototype for ptrace seize
Summary:
This is an internal version of my upstream PR [#137041](https://github.com/llvm/llvm-project/pull/137041) where I'm hacking in PTRACE_SEIZE support for Coredumping processes, and then preventing them from being resumed. We only allow exiting, I've explained this in further detail in my test plan.

This is landing internally first, to give the upstream PR and RFC more time to mature and identify problems or new capabilities we could build on top of this workflow.

Test Plan:
The setup to test this is quite convoluted, and I explain in greater detail in my upstream PR, but to summarize here

I compile this program to hold the kernel provided pipe
```
// Set up the corepipe to our program
echo "|/data/users/jalalonde/sand_test_code/ptrace.out %p" | sudo tee /proc/sys/kernel/core_pattern > /dev/null

Invoke the following:
int main() {
  return 42 / 0;
}
```

This will create a program that is coredumping, I've named this sigabrt. We then use pgrep to find our pid.
```
[jalalonde@devvm17760.vll0 /data/users/jalalonde/sand_test_code]$ pgrep "sigabrt"
3009565
```

And walk through attaching to the coredumping proc, and then trying to continue
```
[jalalonde@devvm17760.vll0 /data/users/jalalonde/llvm-sand/dbg]$ ./bin/lldb
attach 3009565
Process 3009565 stopped
* thread #1, name = 'sigabrt.out', stop reason = signal SIGSTOP
    frame #0: 0x00005618d35b114d sigabrt.out`main at sigabrt.cpp:6:18
   3    }
Executable binary set to "/data/users/jalalonde/sand_test_code/sigabrt.out".
Architecture set to: x86_64-unknown-linux-gnu.
warning: sigabrt.cpp: source file checksum mismatch between line table (69220de0d0b840cdf9c5b92a82466d5e) and file on disk (f76c8c2b73dc057688650908e7e17f34)
(lldb) bt
* thread #1, name = 'sigabrt.out', stop reason = signal SIGSTOP
  * frame #0: 0x00005618d35b114d sigabrt.out`main at sigabrt.cpp:6:18
    frame #1: 0x00007f0233a295d0 libc.so.6`__libc_start_call_main + 128
    frame #2: 0x00007f0233a29680 libc.so.6`__libc_start_main@@GLIBC_2.34 + 128
    frame #3: 0x00005618d35b1065 sigabrt.out`_start + 37
(lldb) continue
error: Failed to resume process: Process is in a non-resumable stop. Only detach or exit are supported..
(lldb) detach
Process 3009565 detached
```

So we succeeded in attaching, moving from 'S' to trace stop 't' and then preventing resumption would kill the proc, this is crucial so data formatters or other code doesn't accidentally resume and kill the process.

Test Matrix
| Case  | LLDB behavior before patch | LLDB Behavior with patch |
|-------|---------------------------------------------------------
| Attach to Root process | Waitpid hang until ctrl-c | Waitpid hang until ctrl-c |
| Attach to Root process coredumping | Waitpid hanging until ctrl-c | Waitpid hanging until ctrl-c |
| Run Expression | N/A Can't attach | Runs without jitting, no error
| Call function | N/A | Fails gracefully with error

Reviewers: gclayton, wanyi, jeffreytan, peix

Reviewed By: gclayton

Subscribers: davidayoung, peix, #lldb_team

Differential Revision: https://phabricator.intern.facebook.com/D73806555