Fix empty source map error from upstream
Summary:
While testing against latest Beta release using fdb, I noticed that VSCode console always emits following failure:

```
Setting source map:
(lldb) settings set target.source-map
error: 'settings set' takes more arguments
```

Turns out fdb is sending empty source map settings to lldb, which lldb has a recent regression to setting empty mapping which causes error.

This diff fixes the regression by detecting the mapping is empty and do not run the command.

This internal patch aims to fix and unblock release immediately, will upstream this later.

Test Plan:
The mentioned error does not show up.
The added test in this diff failed before but pass with the change.

Reviewers: gclayton, peix, #lldb_team, zynli

Reviewed By: zynli

Subscribers: #lldb_team

Differential Revision: https://phabricator.intern.facebook.com/D73478506